name: Release-plz

permissions:
  pull-requests: write
  contents: write

on:
  push:
    branches:
      - main

jobs:
  # Release unpublished packages
  release-plz-release:
    name: Release-plz release
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          clean: true
      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@stable
      - name: Clean workspace
        run: |
          # Remove specific Nix-related files that might cause path issues
          rm -rf .envrc result result-* .direnv || true
          # Remove target directory if it exists
          rm -rf target || true
          # Ensure we have a clean working directory
          git status
      - name: Verify configuration files
        run: |
          echo "Checking for release-plz.toml..."
          ls -la release-plz.toml
          echo "Checking for Cargo.toml..."
          ls -la Cargo.toml
          echo "Current directory contents:"
          ls -la
      - name: Run release-plz
        uses: release-plz/action@v0.5
        with:
          command: release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          CARGO_REGISTRY_TOKEN: ${{ secrets.CARGO_REGISTRY_TOKEN }}
